"""Data awal (seed) JurusanKu: pertanyaan kuis dan katalog jurusan.

Vektor minat jurusan berurutan R, I, A, S, E, C (skala 0-5).
Gaji = estimasi kasar take-home fresh graduate dalam JUTA Rupiah/bulan
(hanya ilustrasi, bervariasi menurut kota, instansi, dan kemampuan).
Field berbentuk daftar dipisah dengan karakter '|'.
"""

DIMS = "RIASEC"
DIM_NAMES = {
    "R": "Realistic (Praktis)", "I": "Investigative (Penyelidik)", "A": "Artistic (Kreatif)",
    "S": "Social (Sosial)", "E": "Enterprising (Pemimpin)", "C": "Conventional (Teratur)",
}
DIM_SHORT = {"R": "Praktis", "I": "Penyelidik", "A": "Kreatif", "S": "Sosial", "E": "Pemimpin", "C": "Teratur"}

# Potensi (radar) dihitung dari skor RIASEC dengan bobot berikut (jumlah bobot = 1).
POTENTIALS = {
    "Logika": {"R": 0.2, "I": 0.5, "C": 0.3},
    "Kreativitas": {"A": 0.7, "I": 0.15, "E": 0.15},
    "Komunikasi": {"S": 0.5, "E": 0.3, "A": 0.2},
    "Analitis": {"I": 0.6, "C": 0.4},
    "Kepemimpinan": {"E": 0.7, "S": 0.3},
}

RUMPUN = ["Saintek", "Soshum", "Campuran"]
JALUR = ["SNBP", "SNBT (UTBK)", "Mandiri PTN", "Jalur PTS / Beasiswa", "Lainnya"]
GROWTH = [(0, 1.0), (3, 1.4), (5, 1.9), (10, 3.0)]  # asumsi pertumbuhan gaji untuk simulasi

# (kategori, dimensi, pernyataan) - jawaban skala 1-5 (sangat tidak setuju - sangat setuju)
QUESTIONS = [
    ("Hobi", "R", "Saya senang memperbaiki, merakit, atau mengutak-atik barang (motor, elektronik, mesin)."),
    ("Hobi", "I", "Saya senang mencari tahu cara kerja sesuatu lewat eksperimen atau riset kecil-kecilan."),
    ("Hobi", "A", "Saya hobi menggambar, mendesain, menulis, bermusik, atau membuat konten kreatif."),
    ("Hobi", "S", "Saya senang membantu teman yang sedang kesulitan atau butuh tempat curhat."),
    ("Hobi", "E", "Saya suka memimpin kegiatan, berjualan, atau meyakinkan orang lain."),
    ("Hobi", "C", "Saya suka merapikan, mencatat, dan mengatur jadwal atau keuangan dengan teliti."),
    ("Mata Pelajaran", "R", "Saya lebih semangat pada pelajaran praktik (prakarya, fisika terapan, olahraga) daripada teori."),
    ("Mata Pelajaran", "I", "Saya menikmati pelajaran seperti Matematika, Fisika, Kimia, atau Biologi."),
    ("Mata Pelajaran", "A", "Saya menikmati pelajaran seni, bahasa, atau sastra."),
    ("Mata Pelajaran", "S", "Saya menikmati pelajaran seperti Sosiologi, BK, atau diskusi kelompok."),
    ("Mata Pelajaran", "E", "Saya menikmati pelajaran Ekonomi, PPKn, atau kegiatan debat dan pidato."),
    ("Mata Pelajaran", "C", "Saya nyaman dengan pelajaran yang jawabannya jelas dan terstruktur, seperti Akuntansi atau Informatika."),
    ("Gaya Belajar", "R", "Saya belajar paling baik dengan praktik langsung, bukan hanya membaca."),
    ("Kepribadian", "I", "Saya penasaran dan sering bertanya 'kenapa' sampai paham akar masalahnya."),
    ("Kepribadian", "A", "Saya lebih suka bebas berkreasi daripada mengikuti aturan yang kaku."),
    ("Gaya Belajar", "S", "Saya lebih mudah paham lewat diskusi dan mengajari teman."),
    ("Kepribadian", "E", "Saya berani mengambil risiko dan percaya diri tampil di depan umum."),
    ("Gaya Belajar", "C", "Saya suka jadwal belajar yang terencana dan target yang jelas."),
]

# (slug, nama, rumpun, (R,I,A,S,E,C), deskripsi, mata kuliah, karier, (gaji_min, gaji_max), plus, minus)
MAJORS = [
    ("teknik-informatika", "Teknik Informatika / Ilmu Komputer", "Saintek", (2, 5, 2, 1, 2, 4),
     "Mempelajari pemrograman, algoritma, basis data, kecerdasan buatan, dan rekayasa perangkat lunak.",
     "Algoritma & Pemrograman|Struktur Data|Basis Data|Jaringan Komputer|Kecerdasan Buatan",
     "Software Engineer|Data Scientist|Cybersecurity Analyst|Product Manager|Founder Startup", (5, 12),
     "Permintaan kerja tinggi dan banyak peluang remote|Gaji kompetitif dengan peluang karier global",
     "Teknologi cepat berubah, harus terus belajar|Persaingan ketat di level junior"),
    ("sistem-informasi", "Sistem Informasi", "Campuran", (1, 4, 2, 2, 3, 5),
     "Menggabungkan teknologi informasi dengan proses bisnis untuk membangun sistem yang membantu organisasi.",
     "Analisis & Perancangan Sistem|Basis Data|Manajemen Proyek TI|ERP|Business Intelligence",
     "Business Analyst|System Analyst|IT Consultant|Project Manager|Data Analyst", (5, 10),
     "Perpaduan teknis dan bisnis, karier fleksibel|Cocok bagi yang tidak ingin coding terlalu berat",
     "Kedalaman teknis lebih sedikit dari Informatika|Perlu portofolio agar menonjol"),
    ("teknik-sipil", "Teknik Sipil", "Saintek", (5, 4, 2, 1, 3, 3),
     "Merancang, membangun, dan merawat infrastruktur seperti gedung, jalan, jembatan, dan bendungan.",
     "Mekanika Teknik|Struktur Beton & Baja|Mekanika Tanah|Hidrologi|Manajemen Konstruksi",
     "Site Engineer|Konsultan Struktur|Pelaksana Proyek|Engineer BUMN Karya|Kontraktor", (5, 9),
     "Proyek infrastruktur terus berjalan|Hasil kerja nyata dan terlihat",
     "Sering bekerja di lapangan dan luar kota|Tanggung jawab keselamatan tinggi"),
    ("teknik-mesin", "Teknik Mesin", "Saintek", (5, 4, 1, 1, 2, 3),
     "Mempelajari desain, produksi, dan perawatan mesin serta sistem energi.",
     "Termodinamika|Mekanika Fluida|Elemen Mesin|Proses Manufaktur|Mesin Konversi Energi",
     "Engineer Manufaktur|Engineer Otomotif|Teknisi Pembangkit|Maintenance Engineer|Peneliti Energi", (5, 9),
     "Lapangan kerja luas di industri dan energi|Fondasi kuat untuk banyak bidang teknik",
     "Banyak perhitungan dan fisika berat|Lingkungan kerja pabrik/lapangan"),
    ("teknik-elektro", "Teknik Elektro", "Saintek", (5, 5, 1, 1, 1, 3),
     "Mempelajari kelistrikan, elektronika, telekomunikasi, dan sistem kendali.",
     "Rangkaian Listrik|Elektronika Digital|Sistem Kendali|Sinyal & Sistem|Sistem Tenaga",
     "Engineer Energi/PLN|Engineer Telekomunikasi|Embedded System Engineer|Automation Engineer|Peneliti", (5, 10),
     "Dibutuhkan di energi, telekomunikasi, dan IoT|Cocok bagi yang suka matematika dan fisika",
     "Materi abstrak dan padat|Persaingan lulusan cukup tinggi"),
    ("teknik-industri", "Teknik Industri", "Saintek", (3, 4, 1, 2, 4, 4),
     "Mengoptimalkan sistem produksi, logistik, dan kualitas agar proses kerja efisien.",
     "Riset Operasi|Perancangan Tata Letak|Pengendalian Kualitas|Ergonomi|Supply Chain Management",
     "Supply Chain Analyst|Quality Engineer|Production Planner|Management Trainee|Konsultan Operasional", (5, 9),
     "Perpaduan teknik dan manajemen, karier fleksibel|Diterima di industri, perbankan, dan konsultan",
     "Bisa terasa 'serba tanggung' tanpa spesialisasi|Lulusan banyak sehingga persaingan ketat"),
    ("kedokteran", "Kedokteran", "Saintek", (2, 5, 1, 5, 2, 2),
     "Pendidikan untuk menjadi dokter yang mendiagnosis, mengobati, dan mencegah penyakit.",
     "Anatomi|Fisiologi|Biokimia|Farmakologi|Ilmu Penyakit Dalam",
     "Dokter Umum|Dokter Spesialis|Peneliti Medis|Dokter Dinas Kesehatan|Dosen Kedokteran", (6, 15),
     "Profesi dihormati dan berdampak langsung|Kebutuhan tenaga dokter selalu tinggi",
     "Studi panjang dan biaya besar|Beban kerja dan tekanan mental tinggi"),
    ("farmasi", "Farmasi", "Saintek", (3, 5, 1, 3, 1, 4),
     "Mempelajari obat: pembuatan, cara kerja, penggunaan, dan pengawasan mutunya.",
     "Kimia Organik|Farmakologi|Farmasetika|Kimia Analisis|Farmasi Klinik",
     "Apoteker|Quality Control Industri Farmasi|Regulatory Affairs|Peneliti Obat|Apoteker Rumah Sakit", (4, 8),
     "Jalur karier jelas (industri, RS, apotek)|Stabil dan terus dibutuhkan",
     "Perlu pendidikan profesi apoteker|Banyak hafalan dan praktikum"),
    ("keperawatan", "Keperawatan", "Saintek", (3, 3, 1, 5, 1, 3),
     "Mempelajari asuhan keperawatan untuk merawat pasien secara menyeluruh.",
     "Anatomi & Fisiologi|Keperawatan Dasar|Keperawatan Medikal Bedah|Keperawatan Anak|Keperawatan Komunitas",
     "Perawat Rumah Sakit|Perawat Komunitas|Perawat Luar Negeri|Dosen Keperawatan|Tenaga Kesehatan Perusahaan", (3, 7),
     "Peluang kerja besar, termasuk luar negeri|Pekerjaan bermakna dan membantu orang",
     "Shift kerja dan beban fisik berat|Gaji awal di dalam negeri relatif sedang"),
    ("statistika", "Statistika / Sains Data", "Saintek", (1, 5, 1, 1, 2, 5),
     "Mempelajari pengumpulan, analisis, dan interpretasi data untuk pengambilan keputusan.",
     "Teori Probabilitas|Inferensi Statistik|Analisis Regresi|Data Mining|Komputasi Statistik",
     "Data Analyst|Data Scientist|Statistisi (BPS)|Actuarial Analyst|Market Researcher", (5, 10),
     "Keahlian data dicari di banyak industri|Landasan kuat untuk AI dan sains data",
     "Matematika intensif|Perlu melengkapi keterampilan pemrograman"),
    ("arsitektur", "Arsitektur", "Campuran", (4, 3, 5, 2, 2, 2),
     "Merancang bangunan dan ruang yang fungsional, aman, dan estetis.",
     "Studio Perancangan|Struktur Bangunan|Sejarah & Teori Arsitektur|Utilitas Bangunan|Perancangan Kota",
     "Arsitek|Desainer Interior|Urban Planner|Konsultan Desain|Drafter BIM", (4, 9),
     "Menggabungkan seni dan teknik|Karya nyata berupa bangunan",
     "Tugas studio menguras waktu dan biaya|Gaji awal belum sebanding beban kerja"),
    ("psikologi", "Psikologi", "Campuran", (1, 4, 2, 5, 2, 2),
     "Mempelajari perilaku dan proses mental manusia serta penerapannya.",
     "Psikologi Perkembangan|Psikologi Sosial|Psikometri|Psikologi Klinis|Metode Penelitian",
     "Psikolog (lanjut Profesi)|HR / Recruiter|Konselor|Peneliti|UX Researcher", (3, 7),
     "Ilmunya berguna dalam kehidupan sehari-hari|Karier beragam: klinis, industri, pendidikan",
     "Menjadi psikolog perlu pendidikan profesi lanjutan|Gaji awal sarjana relatif sedang"),
    ("dkv", "Desain Komunikasi Visual", "Soshum", (1, 2, 5, 2, 3, 1),
     "Mempelajari komunikasi lewat visual: ilustrasi, branding, motion graphic, dan desain antarmuka.",
     "Dasar Desain|Tipografi|Ilustrasi Digital|Desain Branding|Motion Graphic",
     "Graphic Designer|UI/UX Designer|Art Director|Motion Designer|Content Creator", (4, 8),
     "Portofolio sering lebih dinilai daripada ijazah|Peluang freelance dan remote",
     "Persaingan ketat, gaji awal bervariasi|Revisi dari klien bisa melelahkan"),
    ("manajemen", "Manajemen", "Soshum", (1, 2, 2, 3, 5, 4),
     "Mempelajari cara mengelola organisasi, sumber daya, pemasaran, dan keuangan bisnis.",
     "Pengantar Bisnis|Manajemen Pemasaran|Manajemen Keuangan|Manajemen SDM|Kewirausahaan",
     "Marketing Executive|HR Specialist|Management Trainee|Wirausahawan|Product Manager", (4, 8),
     "Fleksibel, bisa masuk hampir semua industri|Bagus untuk membangun bisnis sendiri",
     "Lulusan banyak sehingga persaingan ketat|Perlu keahlian spesifik agar menonjol"),
    ("akuntansi", "Akuntansi", "Soshum", (1, 3, 0, 2, 2, 5),
     "Mempelajari pencatatan, pelaporan, audit, dan analisis keuangan.",
     "Akuntansi Keuangan|Akuntansi Biaya|Auditing|Perpajakan|Sistem Informasi Akuntansi",
     "Auditor|Akuntan Perusahaan|Konsultan Pajak|Analis Keuangan|Akuntan Sektor Publik", (4, 8),
     "Dibutuhkan hampir semua perusahaan|Jalur sertifikasi karier jelas",
     "Detail dan rutinitas tinggi|Musim sibuk saat tutup buku dan audit"),
    ("ilmu-komunikasi", "Ilmu Komunikasi", "Soshum", (0, 2, 4, 4, 4, 1),
     "Mempelajari penyampaian pesan lewat media, humas, jurnalistik, dan komunikasi digital.",
     "Teori Komunikasi|Jurnalistik|Public Relations|Produksi Media|Komunikasi Digital",
     "Public Relations|Jurnalis|Social Media Specialist|Content Strategist|Copywriter", (3, 7),
     "Cocok bagi yang suka bercerita dan berinteraksi|Peluang luas di media digital",
     "Lulusan banyak, perlu portofolio nyata|Gaji awal relatif sedang"),
    ("hukum", "Ilmu Hukum", "Soshum", (0, 3, 1, 4, 5, 3),
     "Mempelajari sistem hukum, peraturan perundang-undangan, dan penegakan keadilan.",
     "Pengantar Ilmu Hukum|Hukum Pidana|Hukum Perdata|Hukum Tata Negara|Hukum Bisnis",
     "Advokat|Jaksa / Hakim (lewat seleksi)|Legal Officer|Konsultan Hukum|Notaris (lanjut)", (4, 10),
     "Jalur karier prestisius dan beragam|Melatih nalar kritis dan argumentasi",
     "Banyak bacaan dan hafalan pasal|Jalur profesi (advokat/notaris) cukup panjang"),
    ("hubungan-internasional", "Hubungan Internasional", "Soshum", (0, 3, 2, 4, 4, 2),
     "Mempelajari hubungan antarnegara: diplomasi, politik global, ekonomi, dan keamanan.",
     "Teori HI|Diplomasi|Ekonomi Politik Internasional|Hukum Internasional|Politik Luar Negeri",
     "Diplomat (lewat seleksi Kemlu)|Analis Kebijakan|Staf NGO / Organisasi Internasional|Peneliti|Jurnalis Internasional", (4, 8),
     "Wawasan global dan jejaring internasional|Cocok bagi yang suka isu dunia",
     "Posisi diplomat sangat kompetitif|Perlu bahasa asing yang kuat"),
    ("pendidikan-guru", "Pendidikan (Keguruan / PGSD)", "Soshum", (1, 2, 3, 5, 3, 3),
     "Menyiapkan calon guru dan pendidik: pedagogik, kurikulum, dan praktik mengajar.",
     "Psikologi Pendidikan|Strategi Pembelajaran|Pengembangan Kurikulum|Evaluasi Pembelajaran|PPL / Magang Mengajar",
     "Guru|Dosen (lanjut S2)|Pengembang Kurikulum|Kreator Konten Edukasi|Trainer / Instruktur", (2, 6),
     "Jalur ASN/PPPK tersedia|Berdampak bagi generasi berikutnya",
     "Gaji awal guru honorer relatif rendah|Beban administrasi cukup besar"),
    ("sastra-inggris", "Sastra Inggris", "Soshum", (0, 3, 5, 3, 2, 2),
     "Mempelajari bahasa, sastra, linguistik, dan penerjemahan bahasa Inggris.",
     "Linguistik|Translation|Literary Studies|Cross-Cultural Understanding|Academic Writing",
     "Penerjemah / Interpreter|Content Writer|Guru Bahasa|Staf Humas|Editor / Penerbit", (3, 7),
     "Kemampuan bahasa bernilai di banyak bidang|Peluang kerja remote dan freelance",
     "Jalur karier tidak selalu linear|Harus ditambah keahlian lain agar menonjol"),
]
